### ISSUE TITLE
Back-off restarting failed container

### ISSUE THREAD

**Issue by SSuperMengNan** [FudanSELab/train-ticket#237]
When deploying with kubernets, most of the services in the yaml2 file appear as back-off restarting failed containers
![image](https://user-images.githubusercontent.com/92978013/188049701-bebfd9dc-fe1a-48a3-b08c-4da12dd7da20.png)

**Comment by ritesh-avesha** [comment]
Try fixing the mongo docker image version to older one. 
Currently there is no tag and it downloads the latest image, which is incompatible.
If you see the logs of any failing container you will find this: 
```
Caused by: org.springframework.data.mongodb.UncategorizedMongoDbException: Query failed with error code 352 and error  
 message 'Unsupported OP_QUERY command: find. The client driver may require an upgrade. For more details see  
 
https://dochub.mongodb.org/core/legacy-opcode-removal' on server ts-auth-mongo:27017; nested exception is  
 
com.mongodb.MongoQueryException: Query failed with error code 352 and error message  
 'Unsupported OP_QUERY command: find. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal' on server ts-auth-mongo:27017
``` 
One workaround is to use and older mongo image, e,g with tag 5.0.10 which is ~3 weeks old from today.
e.g 
Instead of 
```
  spec:  
      containers:
      - name: ts-ticket-office-mongo
        image: mongo
```

Use
```
   spec:    
      containers:  
      - name: ts-ticket-office-mongo  
        image: mongo:5.0.10
```
You need to replace all deployment which use mongo image
